# Generated by Django 5.1.3 on 2024-11-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('ausID', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')])),
                ('fname', models.CharField(max_length=25, unique=True)),
                ('lname', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
