# Generated by Django 5.1.3 on 2024-11-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=45),
        ),
    ]
