# Generated by Django 5.1.3 on 2024-11-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_fname_alter_users_lname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
